### ISSUE TITLE
The program doesn't seem to support HTTPS?

### ISSUE THREAD

**Issue by WindyCloudCute** [hibikikuze4dan/lanraragi-react-web#2]
I’m using Docker image 444f130c4579 and I can’t access HTTPS LANraragi. It seems that there are no settings options that can be modified?

**Comment by hibikikuze4dan** [comment]
> I’m using Docker image 444f130c4579 and I can’t access HTTPS LANraragi. It seems that there are no settings options that can be modified?

Whoops, yeah sorry about that. All of the requests are currently hard coded to be http. Shouldn't be too hard to add a setting to make them one or the other though. I'll get on that tonight.

**Comment by WindyCloudCute** [comment]
I'm glad to hear from you and thank you for making this suggestion an edit. 😀

**Comment by hibikikuze4dan** [comment]
Alright, just [pushed up an update](https://github.com/hibikikuze4dan/lanraragi-react-web/commit/f5920a4ed6a7a2dbbcc916841bd1ffa8fb2dd16f). You should be able to choose whether or not you use http or https by clicking on the new button that should appear next to where you previously entered the server address and then pressing "Set Address" to save the change.


Image of how it looks:
![Screenshot 2023-07-07 170717](https://github.com/hibikikuze4dan/lanraragi-react-web/assets/64999371/06a73b47-4835-4816-81c5-a077330df53f)


Let me know if this solves the issue for you.

**Comment by WindyCloudCute** [comment]
Thank you for fixing this problem, it can run normally now.
