### ISSUE TITLE
The page cannot be scrolled

### ISSUE THREAD

**Issue by chu-shen** [hibikikuze4dan/lanraragi-react-web#5]
On mobile with the 'bottom-navbar', the 'settings' page cannot be scrolled. 

On tablet with the 'side-navbar', only the 'Archive Info' dialog can be scrolled.

**Comment by hibikikuze4dan** [comment]
> On tablet with the 'side-navbar', only the 'Archive Info' dialog can be scrolled.

Was able to resolve the first issue:
https://github.com/hibikikuze4dan/lanraragi-react-web/commit/55daa0d323244844088588d7149ffc98604d577c

I'm having trouble understanding what you mean with the second issue. Are you saying that only the Archive Info dialog can be scrolled when it's open?

**Comment by chu-shen** [comment]
> Was able to resolve the first issue: [55daa0d](https://github.com/hibikikuze4dan/lanraragi-react-web/commit/55daa0d323244844088588d7149ffc98604d577c)

well done👍


> I'm having trouble understanding what you mean with the second issue. Are you saying that only the Archive Info dialog can be scrolled when it's open?

Sorry for that, I meant that the 'random', 'search', 'history', and 'settings' pages cannot be scrolled. Additionally, the reading page cannot be scrolled either. 

Here is a short video to demonstrate the problem.


https://github.com/hibikikuze4dan/lanraragi-react-web/assets/45256288/bd5999ad-18e9-4e88-acbe-7a120018f902

**Comment by hibikikuze4dan** [comment]
Oof, yeah that's an issue. Just from looking at the video I think this might be a browser compatibility issue with some of the code.  What browser app and app version is being used in that video?

**Comment by chu-shen** [comment]
Just upgraded my Chrome browser from version 107.0.5304 to 114, and now it can be scrolled normally. Thanks!
