### ISSUE TITLE
adding more metadata information on the archive thumbnails

### ISSUE THREAD

**Issue by chu-shen** [hibikikuze4dan/lanraragi-react-web#6]
I was wondering if there is any interest in adding more metadata information on the archive thumbnails

such as 'isnew', 'pagecount', 'date_added', as shown in the image below

![](https://github.com/chu-shen/lanraragi-react-web/raw/feat-ratingAndcomment/legend-Tony.png)

**Comment by hibikikuze4dan** [comment]
There is definitely interest. I was planning on doing something along the lines of creating a separate component that acts like the current Archive component but with more details on the front of it like you show in that image and then just adding in a setting for users to decide which way they want to have archives displayed to them.

Is Rating&Comment something currently available on Lanraragi?

**Comment by chu-shen** [comment]
Glad to hear that. Looking forward to your next development plan 👍

In addition, it would be great if we could have the option to choose which metadata tags to display, 
as the metadata tags in my LRR are already converted to my native language - Chinese.

---

> Is Rating&Comment something currently available on Lanraragi?

Unfortunately, I haven't seen any plans for LRR to support Rating & Comment at the moment. https://github.com/Difegue/LANraragi/discussions/382

Currently, I store the information by adding ['Rating'](https://github.com/chu-shen/lanraragi-react-web/blob/188ea11fe4d0b905de50e914551f24e991993cd7/src/components/archive/fragments/archive-metadata-buttons.js#L41) and ['Comment'](https://github.com/chu-shen/lanraragi-react-web/blob/188ea11fe4d0b905de50e914551f24e991993cd7/src/components/archive/fragments/archive-metadata-buttons.js#L57) tags to the [metadata](https://github.com/chu-shen/lanraragi-react-web/blob/188ea11fe4d0b905de50e914551f24e991993cd7/src/requests/metadata.js#L20)

However, since all tags in LRR are stored in the 'tags' field and separated by commas, tags cannot contain commas. 
I'm not sure if this approach is suitable...

---

Furthermore, before discovering the amazing project lanraragi-react-web, I used [a self-made LRR plugin](https://github.com/chu-shen/LANraragi/blob/feat-ratingAndcomment/lib/LANraragi/Plugin/Metadata/Comment.pm) that required modifying the LRR frontend page.
