### ISSUE TITLE
可以上传到docker吗

### ISSUE THREAD

**Issue by kotoriww** [hibikikuze4dan/lanraragi-react-web#7]
可以上传到docker吗,代码编译太麻烦了

**Comment by chu-shen** [comment]
[Check out the wiki](https://github.com/hibikikuze4dan/lanraragi-react-web/wiki/Installation-and-Startup)

wiki 里有 docker 地址 @kotoriww

**Comment by hibikikuze4dan** [comment]
> 可以上传到docker吗,代码编译太麻烦了

Like chu-shen said, a docker image for this app exists here: https://hub.docker.com/r/acreed1998/lrr-react

**Comment by kotoriww** [comment]
ok ty
